repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version
    hooks:
      - id: black
        args:
          - --line-length=88
          - --quiet

  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.6  # Use the latest stable version
    hooks:
      - id: pylint
        args:
          - --disable=import-error
          - --disable=too-many-instance-attributes
          - --disable=too-many-arguments
          - --disable=too-few-public-methods
          - --disable=too-many-locals
          - --disable=too-many-positional-arguments
          - --disable=broad-exception-caught
          - --disable=duplicate-code
          - --disable=too-many-return-statements